In [1]:
from IPython.display import display, HTML 
display(HTML("""
<style>
div.container{width:86% !important;}
div.cell.code_cell.rendered{width:100%;}
div.CodeMirror {font-family:Consolas; font-size:15pt;}
div.output {font-size:15pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:15pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:15px;}
</style>
"""))

<b><font size="5" color="red">ch14_웹데이터수집2_동적</font></b>
## 3절. 동적 웹데이터 수집
```
    pip install selenium
```
- Docs : https://www.selenium.dev/documentation/, https://selenium-python.readthedocs.io/

In [27]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import time
driver = webdriver.Chrome()
driver.get("http://www.python.org")
elem = driver.find_element(By.NAME, 'q')
elem.clear()
elem.send_keys('pycon')
from selenium.webdriver.common.keys import Keys
elem.send_keys(Keys.RETURN) # enter 효과

In [12]:
result_list = driver.find_elements(By.CSS_SELECTOR, 'li > h3 > a')
for result in result_list:
    print('{} - {}'.format(result.text, result.get_attribute('href')))

PSF PyCon Trademark Usage Policy - https://www.python.org/psf/trademarks/pycon
PyCon Italia 2016 (PyCon Sette) - https://www.python.org/events/python-events/378/
PyCon Australia 2013 - https://www.python.org/events/python-events/57/
PyCon AU 2019 - https://www.python.org/events/python-events/776/
PyCon Australia 2014 - https://www.python.org/events/python-events/10/
PyCon Ireland 2012 - https://www.python.org/events/python-events/76/
PyCon Ireland 2016 - https://www.python.org/events/python-events/429/
PyCon Ireland 2022 - https://www.python.org/events/python-events/1320/
PyCon Australia 2014 - https://www.python.org/events/python-events/1447/
PyCon Ireland 2024 - https://www.python.org/events/python-events/1862/
PyCon APAC 2025 - https://www.python.org/events/python-events/1879/
PyCon AU 2018 - https://www.python.org/events/python-events/696/
PyCon APAC 2022 - https://www.python.org/events/python-events/1216/
PyCon PH 2024 - https://www.python.org/events/python-events/1661/
PyCon Ireland 2023 - https://www.python.org/events/python-events/1568/
PyCon PL 2014 - https://www.python.org/events/python-events/191/
PyCon MY 2015 - https://www.python.org/events/python-events/313/
PyCon Ireland 2015 - https://www.python.org/events/python-events/333/
PyCon AU 2015 - https://www.python.org/events/python-events/273/
PyCon Australia 2016 - https://www.python.org/events/python-events/357/

In [19]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(driver.page_source, 'html.parser')
result_list = soup.select('li> h3 >a')
for result in result_list:
    print('{} - {}'.format(result.text, result.attrs['href']))

PSF PyCon Trademark Usage Policy - /psf/trademarks/pycon
PyCon Italia 2016 (PyCon Sette) - /events/python-events/378/
PyCon Australia 2013 - /events/python-events/57/
PyCon AU 2019 - /events/python-events/776/
PyCon Australia 2014 - /events/python-events/10/
PyCon Ireland 2012 - /events/python-events/76/
PyCon Ireland 2016 - /events/python-events/429/
PyCon Ireland 2022 - /events/python-events/1320/
PyCon Australia 2014 - /events/python-events/1447/
PyCon Ireland 2024 - /events/python-events/1862/
PyCon APAC 2025 - /events/python-events/1879/
PyCon AU 2018 - /events/python-events/696/
PyCon APAC 2022 - /events/python-events/1216/
PyCon PH 2024 - /events/python-events/1661/
PyCon Ireland 2023 - /events/python-events/1568/
PyCon PL 2014 - /events/python-events/191/
PyCon MY 2015 - /events/python-events/313/
PyCon Ireland 2015 - /events/python-events/333/
PyCon AU 2015 - /events/python-events/273/
PyCon Australia 2016 - /events/python-events/357/

In [18]:
# 셀레니움을 통해 접근한 현재 url
from urllib.parse import urlparse
current_url = driver.current_url
print('현재 주소 : ', current_url)
parse_url = urlparse(current_url)
print('parse_url: ', parse_url)
domain = f'{parse_url.scheme}://{parse_url.netloc}'
print(domain)

현재 주소 :  https://www.python.org/search/?q=pycon&submit=
parse_url:  ParseResult(scheme='https', netloc='www.python.org', path='/search/', params='', query='q=pycon&submit=', fragment='')
https://www.python.org

In [25]:
soup = BeautifulSoup(driver.page_source, 'html.parser')
result_list = soup.select('li> h3 >a')
for result in result_list:
    print('{} - {}'.format(result.text, domain+result.attrs['href']))

PSF PyCon Trademark Usage Policy - https://www.python.org/psf/trademarks/pycon
PyCon Italia 2016 (PyCon Sette) - https://www.python.org/events/python-events/378/
PyCon Australia 2013 - https://www.python.org/events/python-events/57/
PyCon AU 2019 - https://www.python.org/events/python-events/776/
PyCon Australia 2014 - https://www.python.org/events/python-events/10/
PyCon Ireland 2012 - https://www.python.org/events/python-events/76/
PyCon Ireland 2016 - https://www.python.org/events/python-events/429/
PyCon Ireland 2022 - https://www.python.org/events/python-events/1320/
PyCon Australia 2014 - https://www.python.org/events/python-events/1447/
PyCon Ireland 2024 - https://www.python.org/events/python-events/1862/
PyCon APAC 2025 - https://www.python.org/events/python-events/1879/
PyCon AU 2018 - https://www.python.org/events/python-events/696/
PyCon APAC 2022 - https://www.python.org/events/python-events/1216/
PyCon PH 2024 - https://www.python.org/events/python-events/1661/
PyCon Ireland 2023 - https://www.python.org/events/python-events/1568/
PyCon PL 2014 - https://www.python.org/events/python-events/191/
PyCon MY 2015 - https://www.python.org/events/python-events/313/
PyCon Ireland 2015 - https://www.python.org/events/python-events/333/
PyCon AU 2015 - https://www.python.org/events/python-events/273/
PyCon Australia 2016 - https://www.python.org/events/python-events/357/

In [28]:
driver.close()

## 3.2 예제
### 1) 다음뉴스 검색

In [47]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time

driver = webdriver.Chrome()
driver.get("http://www.daum.net/")
# input태그를 click
time.sleep(1)
driver.find_element(By.NAME, 'q').click()
query = input('검색하고자 하는 단어는?')
driver.find_element(By.CSS_SELECTOR, 'input[type="text"]').send_keys(query)
driver.find_element(By.CLASS_NAME, 'btn_ksearch').click()
time.sleep(2)
# 뉴스탭 클릭 : ul.list_tab > li
# driver.find_elements(By.CSS_SELECTOR, 'ul.list_tab > li')[3].click()
driver.find_element(By.LINK_TEXT, '뉴스').click()
time.sleep(2)
news_list = []
elems = driver.find_elements(By.CSS_SELECTOR, 'div.item-title > strong.tit-g > a')
for elem in elems:
    title = elem.text
    link = elem.get_attribute('href')
    news_list.append([title, link])
    print(title, link)

검색하고자 하는 단어는?MAGA
[시론] 트럼프 MAGA 정책은 위기이자 기회다 http://v.daum.net/v/20250529002629255
트럼프 사면의 법칙…MAGA 충성하거나 금융범죄자거나 http://v.daum.net/v/20250529112120497
日대표에 ‘MAGA 모자’ 씌운 트럼프, ‘충성 연출’ 논란 http://v.daum.net/v/20250420070848540
Trump’s MAGA trade policy: A crisis, but also an opportunity for Korea http://v.daum.net/v/20250529000350877
'너도 기자냐고? 그러는 네가 가짜야' MAGA 미디어의 역습 [World Now] http://v.daum.net/v/20250428103111009
교황의 맏형은 'MAGA' 지지자…"오바마가 독재 · 인종차별" 주장 http://v.daum.net/v/20250515053302860
‘MAGA 모자’ 中 공장 가보니 원가 4000원… “세계서 여기만 가능” http://v.daum.net/v/20250506005304831
교황 큰 형은 정치적 극우 성향 드러내 온 'MAGA' 지지자 http://v.daum.net/v/20250514170255961
[세계를 가다]MAGA ‘NO’ 푸른색 ‘NO’…“정치대화 금지” 식당 http://v.daum.net/v/20250505195644626
트럼프, 대통령 하면서 가족은 3조 벌었다…MAGA도 "이건 뇌물" http://v.daum.net/v/20250515142011575

In [50]:
# 2page로
page_div = driver.find_element(By.CSS_SELECTOR, 'div.inner_paging')
# print(page_div.text)
next_page = page_div.find_element(By.LINK_TEXT, '2')
next_page.click()

1 2 3 4 5

In [54]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time

driver = webdriver.Chrome()
driver.get("http://www.daum.net/")
# input태그를 click
time.sleep(1)
driver.find_element(By.NAME, 'q').click()
query = input('검색하고자 하는 단어는?')
driver.find_element(By.CSS_SELECTOR, 'input[type="text"]').send_keys(query)
driver.find_element(By.CLASS_NAME, 'btn_ksearch').click()
time.sleep(2)
# 뉴스탭 클릭 : ul.list_tab > li
# driver.find_elements(By.CSS_SELECTOR, 'ul.list_tab > li')[3].click()
driver.find_element(By.LINK_TEXT, '뉴스').click()
time.sleep(2)
news_list = []
pages = 3
for page in range(1,pages+1):
    elems = driver.find_elements(By.CSS_SELECTOR, 'div.item-title > strong.tit-g > a')
    for elem in elems:
        title = elem.text
        link = elem.get_attribute('href')
        news_list.append([title, link])
        
    # 2page로
    page_div = driver.find_element(By.CSS_SELECTOR, 'div.inner_paging')
    # print(page_div.text)
    next_page = page_div.find_element(By.LINK_TEXT, str(page+1))
    next_page.click()
    time.sleep(1.5)
    print(f'~~ 현재 {page}페이지 데이터를 수집 중입니다~~')
driver.close()
import pandas as pd
df = pd.DataFrame(news_list, columns=['title','link'])
df.to_csv('data/ch14_daum.csv', index=False, encoding='cp949')

검색하고자 하는 단어는?투표율
~~ 현재 1페이지 데이터를 수집 중입니다~~
~~ 현재 2페이지 데이터를 수집 중입니다~~
~~ 현재 3페이지 데이터를 수집 중입니다~~

### 2) 맞춤법 검사기
- 네이버 맞춤법 검사기

In [1]:
# f = open('data/ch14_맞춤법전.txt', 'r', encoding='utf-8')
# text = f.read()
# f.close()

In [3]:
# ch14_맞춤법전.txt를 300자이내로 자르기
with open('data/ch14_맞춤법검사전.txt', 'r', encoding='utf-8') as f:
    text = f.read()
print('총글자 수 :',len(text))
ready_list = [] # 맞춤법 검사할 text 내용(300이자 이내로 list)
while(len(text) > 300):
    temp = text[:300]
    new_line_char_index = temp.rfind('\n')
    print(new_line_char_index)
    ready_list.append(text[:new_line_char_index])
    text = text[new_line_char_index:]
ready_list.append(text)
[ready[:10] for ready in ready_list]

총글자 수 : 1785
242
170
156
204
283
295
136

['안냥하십니까> P ',
 '\n가장 큰 문제는 ',
 '\n또한, 투자자 보',
 '\n운영 방식에서도 ',
 '\n정보의 투명성도 ',
 '\n둘째, 투자자 보',
 '\n넷째, 국내외 사',
 '\n결론적으로, P2']

In [13]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from bs4 import BeautifulSoup
import time
driver = webdriver.Chrome()

time.sleep(0.5)
driver.get('https://www.naver.com/')
input_elem = driver.find_element(By.CSS_SELECTOR, 'input[name="query"]')
input_elem.send_keys('맞춤법 검사기')
input_elem.send_keys(Keys.RETURN)

time.sleep(0.5)
results ='' # 맞춤법 검사후 내용
textarea = driver.find_element(By.CLASS_NAME, 'txt_gray')
for ready in ready_list:
    time.sleep(2)

    textarea.send_keys(Keys.CONTROL,'a') # control + a
    textarea.send_keys(ready)

    button = driver.find_element(By.CLASS_NAME, 'btn_check')
    button.click()
    time.sleep(2)
    soup = BeautifulSoup(driver.page_source, 'html.parser')
    result = soup.select_one('p._result_text.stand_txt').text
    results += result + '\n\n'
driver.close()

with open('data/ch14_맞춤법점검후.txt', 'w', encoding='utf-8') as f:
    f.write(results)

In [21]:
# ch14_맞춤법점검전.txt를 1000자이내로 자르기
with open('data/ch14_맞춤법검사전.txt', 'r', encoding='utf-8') as f:
    text = f.read()
print('총글자 수 :',len(text))
ready_list = [] # 맞춤법 검사할 text 내용(300이자 이내로 list)
while(len(text) > 1000):
    temp = text[:1000]
    new_line_char_index = temp.rfind('\n')
    ready_list.append(text[:new_line_char_index])
    text = text[new_line_char_index:]
ready_list.append(text)
print('번역할 한글 수:', [len(ready) for ready in ready_list])

총글자 수 : 1016
번역할 한글 수: [932, 84]

In [22]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from bs4 import BeautifulSoup
import time

driver = webdriver.Chrome()
time.sleep(0.5)

driver.get('https://www.daum.net/')
input_elem = driver.find_element(By.CSS_SELECTOR, 'input[name="q"]')
input_elem.send_keys('한국어번역기')
input_elem.send_keys(Keys.RETURN)
time.sleep(0.5)

results ='' # 맞춤법 검사후 내용
textarea = driver.find_element(By.CSS_SELECTOR, 'textarea.translate_area.area_item.translate_many')
button = driver.find_element(By.CSS_SELECTOR, 'div.btn_item')

for ready in ready_list:
    time.sleep(2)
    print('~~~ 번역중 ~~~')
    textarea.send_keys(Keys.CONTROL,'a') # control + a
    textarea.send_keys(ready)
    
    button.click()
    time.sleep(2) 
    
    soup = BeautifulSoup(driver.page_source, 'html.parser')
    result = soup.select_one('div.result_area').text
    results += result + '\n\n'
driver.close()

with open('data/ch14_영어번역후.txt', 'w', encoding='utf-8') as f:
    f.write(results)

~~~ 번역중 ~~~
~~~ 번역중 ~~~

### 3) 나혼자 연습
#### 네이버/금융/증권/주가총액

In [17]:
a=[1,2,3]
a.insert(2,'a')
a

[1, 2, 'a', 3]

In [61]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from bs4 import BeautifulSoup
from urllib.request import urlopen
import math
import time
import requests
import pandas as pd

driver = webdriver.Chrome() 
driver.get('https://finance.naver.com/sise/sise_market_sum.naver?sosok=1')
time.sleep(0.5) # 초기화면 접근

no_tgl_bxs = len(driver.find_elements(By.CSS_SELECTOR, 'td > input[type="checkbox"]'))
toggle_boxes = [f'option{i}' for i in range(1, no_tgl_bxs+1)] # 체크박스 이름 준비

pageN = 10
max_tgl = 6
item_list = pd.DataFrame([])
for page in range(1,pageN+1):
    page_item_list = []
    for sheet in range(0, math.ceil(no_tgl_bxs/max_tgl)):
        dflt_toggle_boxes = driver.find_elements(By.CSS_SELECTOR, 'td.choice > input[type="checkbox"]')
        [elem.send_keys(Keys.SPACE) for elem in dflt_toggle_boxes]
        time.sleep(0.5) # 디폴트 체크박스 toggle
        
        sheet_toggle_boxes = toggle_boxes[sheet*max_tgl:min((sheet+1)*max_tgl, no_tgl_bxs+1)]
        new_toggle_boxes = [select_box for select_box in sheet_toggle_boxes]
        [driver.find_element(By.ID, box_id).send_keys(Keys.SPACE) for box_id in new_toggle_boxes]
        time.sleep(0.5) # 시트별 새로운 체크박스 toggle
        driver.find_element(By.CSS_SELECTOR, 'div.item_btn > a').click()
        time.sleep(0.5) # 토글 체크후 submit버튼 클릭

        print(f'~~ 현재 {page}페이지 {sheet}시트 데이터를 수집 중입니다~~')

        soup = BeautifulSoup(driver.page_source, 'html.parser')
        table_head = [e.text.strip() for e in soup.select('thead > tr >th')][:-1]
        table_head.insert(3, '전일비변동')
        items = soup.select('tbody > tr') # 테이블 헤드 수집
        sheet_item_list = []
        for idx, item in enumerate(items):
            if(item.select_one('td.no')):
                no = item.select_one('td.no').text
                title = item.select_one('a.tltle').text
                price_vals = [e.text.strip() for e in item.select('td.number')]
                if(price_vals[1].strip()=='보합0'):
                    price_vals[1]=['보합',0]
                else:
                    price_vals[1] = [price_vals[1].split('\n')[0], price_vals[1].split('\n')[1].strip()]

                price_vals.insert(0, no)
                price_vals.insert(1, title)
                temp = price_vals[3][1]
                price_vals.insert(3,price_vals[3][0])
                price_vals[4] = temp

                sheet_item_list.append(price_vals) # 테이블 내용 수집 
        sheet_item_df = pd.DataFrame(sheet_item_list, columns=table_head)

        if sheet == 0:
            page_item_list = sheet_item_df
        elif sheet < round(no_tgl_bxs/max_tgl):
            page_item_list = pd.concat([page_item_list, sheet_item_df[table_head[6:12]]], axis=1)
        else: 
            page_item_list = pd.concat([page_item_list, sheet_item_df[table_head[6:8]]], axis=1)
            # 페이지 내 시트 축적
    item_list = pd.concat([item_list, page_item_list], axis=0) # 페이지 내용 축적
    
    page_div = driver.find_element(By.CSS_SELECTOR, 'table.Nnavi > tbody > tr')
    if(page<pageN): # 지정 마지막 페이지 초과(pageN+1) 이동 금지
        page_div.find_element(By.LINK_TEXT, str(page+1)).click()
        time.sleep(1.5) # next page로
    
item_list.to_csv(f'data/naver/fin_ksd_gsum_{time.strftime("%y%m%d", time.localtime())}.csv', index=False, encoding='cp949')
item_list.sample(10)

~~ 현재 1페이지 0시트 데이터를 수집 중입니다~~
~~ 현재 1페이지 1시트 데이터를 수집 중입니다~~
~~ 현재 1페이지 2시트 데이터를 수집 중입니다~~
~~ 현재 1페이지 3시트 데이터를 수집 중입니다~~
~~ 현재 1페이지 4시트 데이터를 수집 중입니다~~
~~ 현재 2페이지 0시트 데이터를 수집 중입니다~~
~~ 현재 2페이지 1시트 데이터를 수집 중입니다~~
~~ 현재 2페이지 2시트 데이터를 수집 중입니다~~
~~ 현재 2페이지 3시트 데이터를 수집 중입니다~~
~~ 현재 2페이지 4시트 데이터를 수집 중입니다~~
~~ 현재 3페이지 0시트 데이터를 수집 중입니다~~
~~ 현재 3페이지 1시트 데이터를 수집 중입니다~~
~~ 현재 3페이지 2시트 데이터를 수집 중입니다~~
~~ 현재 3페이지 3시트 데이터를 수집 중입니다~~
~~ 현재 3페이지 4시트 데이터를 수집 중입니다~~
~~ 현재 4페이지 0시트 데이터를 수집 중입니다~~
~~ 현재 4페이지 1시트 데이터를 수집 중입니다~~
~~ 현재 4페이지 2시트 데이터를 수집 중입니다~~
~~ 현재 4페이지 3시트 데이터를 수집 중입니다~~
~~ 현재 4페이지 4시트 데이터를 수집 중입니다~~
~~ 현재 5페이지 0시트 데이터를 수집 중입니다~~
~~ 현재 5페이지 1시트 데이터를 수집 중입니다~~
~~ 현재 5페이지 2시트 데이터를 수집 중입니다~~
~~ 현재 5페이지 3시트 데이터를 수집 중입니다~~
~~ 현재 5페이지 4시트 데이터를 수집 중입니다~~
~~ 현재 6페이지 0시트 데이터를 수집 중입니다~~
~~ 현재 6페이지 1시트 데이터를 수집 중입니다~~
~~ 현재 6페이지 2시트 데이터를 수집 중입니다~~
~~ 현재 6페이지 3시트 데이터를 수집 중입니다~~
~~ 현재 6페이지 4시트 데이터를 수집 중입니다~~
~~ 현재 7페이지 0시트 데이터를 수집 중입니다~~
~~ 현재 7페이지 1시트 데이터를 수집 중입니다~~
~~ 현재 7페이지 2시트 데이터를 수집 중입니다~~
~~ 현재 7페이지 3시트 데이터를 수집 중입니다~~
~~ 현재 7페이지 4시트 데이터를 수집 중입니다~~
~~ 현재 8페이지 0시트 데이터를 수집 중입니다~~
~~ 현재 8페이지 1시트 데이터를 수집 중입니다~~
~~ 현재 8페이지 2시트 데이터를 수집 중입니다~~
~~ 현재 8페이지 3시트 데이터를 수집 중입니다~~
~~ 현재 8페이지 4시트 데이터를 수집 중입니다~~
~~ 현재 9페이지 0시트 데이터를 수집 중입니다~~
~~ 현재 9페이지 1시트 데이터를 수집 중입니다~~
~~ 현재 9페이지 2시트 데이터를 수집 중입니다~~
~~ 현재 9페이지 3시트 데이터를 수집 중입니다~~
~~ 현재 9페이지 4시트 데이터를 수집 중입니다~~
~~ 현재 10페이지 0시트 데이터를 수집 중입니다~~
~~ 현재 10페이지 1시트 데이터를 수집 중입니다~~
~~ 현재 10페이지 2시트 데이터를 수집 중입니다~~
~~ 현재 10페이지 3시트 데이터를 수집 중입니다~~
~~ 현재 10페이지 4시트 데이터를 수집 중입니다~~

,N,종목명,현재가,전일비변동,전일비,등락률,액면가,거래량,거래대금,매수호가,...,당기순이익,외국인비율,액면가,저가,매도총잔량,상장주식수,매출액,주당순이익,액면가,보통주배당금
11,12,삼천당제약,"145,200",하락,800,-0.55%,500,"112,248","16,425","145,100",...,-51,3.16,500,"144,200","1,627","23,457","2,109",-494,500,200
22,373,로체시스템즈,"14,000",하락,140,-0.99%,500,"39,806",561,"14,000",...,121,42.89,500,"13,960","1,519","15,297","1,601",919,500,50
48,449,드림시큐리티,"3,570",상승,70,+2.00%,100,"171,616",607,"3,565",...,121,3.14,100,"3,475","16,190","50,606","2,688",235,100,N/A
18,69,레이크머티리얼즈,"12,550",상승,470,+3.89%,100,"318,138","4,007","12,550",...,210,6.99,100,"12,250","2,376","65,731","1,387",281,100,50
32,383,탑머티리얼,"25,850",하락,800,-3.00%,500,"46,356","1,217","25,850",...,-82,0.00,500,"25,400",633,"8,144","1,061","-1,353",500,0
33,384,디지털대성,"7,600",하락,110,-1.43%,500,"21,524",163,"7,550",...,161,3.15,500,"7,510","2,705","27,675","2,177",583,500,500
11,162,한국기업평가,"96,400",상승,400,+0.42%,"5,000","3,303",317,"96,000",...,286,80.78,"5,000","95,400",705,"4,541","1,041","5,552","5,000","3,954"
28,279,씨메스,"23,950",상승,950,+4.13%,500,"73,500","1,751","23,900",...,-135,2.37,500,"23,350","4,146","11,608",69,"-1,402",500,N/A
16,17,JYP Ent.,"76,800",하락,200,-0.26%,500,"397,084","30,637","76,700",...,977,22.44,500,"76,400","19,090","35,532","6,018","3,811",500,534
13,64,로보티즈,"68,100",상승,"5,500",+8.79%,500,"1,185,713","79,138","68,000",...,-30,10.23,500,"63,500","16,503","13,213",300,51,500,0

In [60]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from bs4 import BeautifulSoup
from urllib.request import urlopen
import time
import requests
import pandas as pd

driver = webdriver.Chrome()
driver.get('https://finance.naver.com/sise/sise_market_sum.naver')
time.sleep(0.5)


new_toggle_boxs = ['option6', 'option12', 'option18', 'option23', 'option24', 'option27']
[driver.find_element(By.ID, box_id).send_keys(Keys.SPACE) for box_id in new_toggle_boxs]
time.sleep(0.5)
driver.find_element(By.CSS_SELECTOR, 'div.item_btn > a').click()
time.sleep(2)
pageN = 10
item_list = []
for page in range(1,pageN+1):
    print(f'~~ 현재 {page}페이지 데이터를 수집 중입니다~~')
#    url = f'https://finance.naver.com/sise/sise_market_sum.naver?sosok=0&page={page}'
#    response = requests.get(url)
    soup = BeautifulSoup(driver.page_source, 'html.parser')

#    items = soup.select('td.choice')
#    selected_items = [e.text.strip() for e in items]
    table_head = [e.text.strip() for e in soup.select('thead > tr >th')]
    items = soup.select('tbody > tr')
    for idx, item in enumerate(items):
        if(item.select_one('td.no')):
            no = item.select_one('td.no').text
            title = item.select_one('a.tltle').text
            price_vals = [e.text.strip() for e in item.select('td.number')]
            if(price_vals[1].strip()=='보합0'):
                price_vals[1]=['보합',0]
            else:
                price_vals[1] = [price_vals[1].split('\n')[0], price_vals[1].split('\n')[1].strip()]

            item_list.append({
                table_head[0]:no,
                table_head[1]:title,
                table_head[2]:price_vals[0],
                '전일비변동':price_vals[1][0],
                table_head[3]:price_vals[1][1],
                table_head[4]:price_vals[2],
                table_head[5]:price_vals[3],
                table_head[6]:price_vals[4],
                table_head[7]:price_vals[5],
                table_head[8]:price_vals[6],
                table_head[9]:price_vals[7],
                table_head[10]:price_vals[8],
                table_head[11]:price_vals[9],
            })

    # next page로
    page_div = driver.find_element(By.CSS_SELECTOR, 'table.Nnavi > tbody > tr')
    if(page<pageN): # 지정 마지막 페이지 초과(pageN+1) 이동 금지
        page_div.find_element(By.LINK_TEXT, str(page+1)).click()
        time.sleep(1.5)
    
df = pd.DataFrame(item_list)
df.to_csv(f'data/naver/fin_gsum_{time.strftime("%y%m%d", time.localtime())}.csv', index=False, encoding='cp949')
df.sample(10)

~~ 현재 1페이지 데이터를 수집 중입니다~~

UnexpectedAlertPresentException: Alert Text: 최대 6개까지만 가능합니다.
Message: unexpected alert open: {Alert text : 최대 6개까지만 가능합니다.}
  (Session info: chrome=137.0.7151.56)
Stacktrace:
	GetHandleVerifier [0x0x7ff670c1fea5+79173]
	GetHandleVerifier [0x0x7ff670c1ff00+79264]
	(No symbol) [0x0x7ff6709d9e5a]
	(No symbol) [0x0x7ff670a81bc0]
	(No symbol) [0x0x7ff670a58743]
	(No symbol) [0x0x7ff670a214c1]
	(No symbol) [0x0x7ff670a22253]
	GetHandleVerifier [0x0x7ff670eea2dd+3004797]
	GetHandleVerifier [0x0x7ff670ee472d+2981325]
	GetHandleVerifier [0x0x7ff670f03380+3107360]
	GetHandleVerifier [0x0x7ff670c3aa2e+188622]
	GetHandleVerifier [0x0x7ff670c422bf+219487]
	GetHandleVerifier [0x0x7ff670c28df4+115860]
	GetHandleVerifier [0x0x7ff670c28fa9+116297]
	GetHandleVerifier [0x0x7ff670c0f558+11256]
	BaseThreadInitThunk [0x0x7ffa43ade8d7+23]
	RtlUserThreadStart [0x0x7ffa44b9c5dc+44]

#### 네이버/금융/증권/배당

In [58]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from bs4 import BeautifulSoup
from urllib.request import urlopen
import time
import requests
import pandas as pd

driver = webdriver.Chrome()
driver.get('https://finance.naver.com/sise/dividend_list.naver')
time.sleep(0.5)
soup = BeautifulSoup(driver.page_source, 'html.parser')

table_head = [e.text.strip() for e in soup.select('thead > tr > th')]
table_head[9] = '과거3년배당금_Max'
driver.find_element(By.LINK_TEXT, '배당금').click()
time.sleep(2)

pageN = 10
item_list = []
for page in range(1,pageN+1):
    print(f'~~ 현재 {page}페이지 데이터를 수집 중입니다~~')

    items = soup.select('table.type_1.tb_ty> tbody > tr')
    for idx, item in enumerate(items):
        if(item.text.strip()):
            price_vals = [e.text.strip().replace(',','').replace('-','0') for e in item.select('td')]
            price_vals.insert(9, max(price_vals[9:12]))
            
            item_list.append({table_head[i]:e for i, e in enumerate(price_vals)})

    # next page로
    page_div = driver.find_element(By.CSS_SELECTOR, 'table.Nnavi > tbody > tr')
    if(page<pageN): # 지정 마지막 페이지 초과(pageN+1) 이동 금지
        page_div.find_element(By.LINK_TEXT, str(page+1)).click()
        time.sleep(1.5)
    
df = pd.DataFrame(item_list)
df.to_csv(f'data/naver/fin_div_{time.strftime("%y%m%d", time.localtime())}.csv', index=False, encoding='cp949')
df.sample(10)

~~ 현재 1페이지 데이터를 수집 중입니다~~
~~ 현재 2페이지 데이터를 수집 중입니다~~
~~ 현재 3페이지 데이터를 수집 중입니다~~
~~ 현재 4페이지 데이터를 수집 중입니다~~
~~ 현재 5페이지 데이터를 수집 중입니다~~
~~ 현재 6페이지 데이터를 수집 중입니다~~
~~ 현재 7페이지 데이터를 수집 중입니다~~
~~ 현재 8페이지 데이터를 수집 중입니다~~
~~ 현재 9페이지 데이터를 수집 중입니다~~
~~ 현재 10페이지 데이터를 수집 중입니다~~

,종목명,현재가,기준월,배당금,수익률(%),배당성향(%),ROE(%),PER(배),PBR(배),과거3년배당금_Max,1년전,2년전,3년전
249,에스에이엠티,2815,24.12,200,7.11,35.89,13.46,4.79,0.59,230,200,230,200
270,현대차우,149900,25.02,12050,8.04,25.13,12.43,4.60,0.51,7050,11450,7050,5050
22,노바텍,17680,24.12,1409,7.97,80.44,10.80,8.95,0.87,500,500,200,143
288,HS애드,7430,25.03,550,7.40,39.29,11.77,4.63,0.51,450,450,400,350
170,현대차우,149900,25.02,12050,8.04,25.13,12.43,4.60,0.51,7050,11450,7050,5050
455,제이알글로벌리츠,2755,24.12,390,14.16,186.25,2.48,26.31,0.67,385,385,373,366
487,스카이라이프,4720,24.12,350,7.41,012.18,021.72,01.65,0.41,350,350,350,350
318,현대해상,25100,24.03,2063,8.22,28.16,7.38,4.82,0.40,1965,1965,1480,1000
412,정다운,2730,24.12,250,9.16,68.61,9.33,7.31,0.65,300,300,100,100
43,KISCO홀딩스,24750,24.12,1800,7.27,70.13,2.82,9.94,0.21,900,900,600,400

In [29]:
a=['12,000','3','4']
max(a)
# str(sum([float(e.replace(',','')) for e in a]))

'4'

In [7]:
import pandas as pd
import time

def load_kospi_sum(str):
    date = time.strftime("%y%m%d", time.localtime())
    item_list = pd.read_csv(f'data/naver/fin_{str}_{date}.csv', encoding='cp949') 
    return item_list

kospi, kosdak, divident = 'gsum', 'ksd_gsum', 'div'
kospi_item_list = load_kospi_sum(kospi)
kosdak_item_list = load_kospi_sum(kosdak)
divident_item_list = load_kospi_sum(divident)

,N,종목명,현재가,전일비변동,전일비,등락률,액면가,거래량,거래대금,매수호가,...,당기순이익,외국인비율,액면가.3,저가,매도총잔량,상장주식수,매출액,주당순이익,액면가.4,보통주배당금
0,1,삼성전자,"57,800",상승,"1,000",+1.76%,100,"19,390,304","1,115,403","57,700",...,"344,514",49.64,100,"56,800","2,228,750","5,919,638","3,008,709","5,162",100,"1,446"
1,2,SK하이닉스,"217,500",상승,"10,000",+4.82%,"5,000","4,997,967","1,096,484","217,500",...,"197,969",54.41,"5,000","216,500","441,034","728,002","661,930","35,682","5,000","2,204"
2,3,삼성바이오로직스,"1,034,000",상승,"3,000",+0.29%,"2,500","78,581","81,007","1,033,000",...,"10,833",12.86,"2,500","1,025,000","9,469","71,174","45,473","17,977","2,500",0
3,4,LG에너지솔루션,"288,500",상승,"4,000",+1.41%,500,"214,348","61,973","288,000",...,"3,386",4.03,500,"286,000","25,353","234,000","256,196","-4,974",500,NaN
4,5,KB금융,"107,900",상승,"7,900",+7.90%,"5,000","2,292,671","241,743","107,900",...,"50,286",75.49,"5,000","100,600","45,973","393,528","850,764","12,705","5,000","3,174"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,지누스,"16,650",하락,90,-0.54%,500,"134,874","2,220","16,600",...,-68,10.15,500,"16,220","2,304","22,255","9,204","1,136",500,90
496,497,제주은행,"9,720",상승,450,+4.85%,"5,000","262,117","2,525","9,720",...,104,2.42,"5,000","9,340","22,552","37,799","3,797",324,"5,000",100
497,498,엘브이엠씨홀딩스,"1,899",상승,43,+2.32%,0,"504,312",953,"1,899",...,42,11.09,0,"1,852","6,656","193,240","2,957",7,0,0
498,499,HANARO 200,"37,230",상승,"1,030",+2.85%,0,"245,737","9,055","37,225",...,NaN,20.57,0,"36,635","74,495","9,850",NaN,NaN,0,NaN
499,500,남해화학,"7,380",상승,70,+0.96%,"1,000","355,152","2,641","7,380",...,215,3.61,"1,000","7,290","5,575","49,679","15,191",498,"1,000",80