In [1]:
from IPython.display import display, HTML 
display(HTML("""
<style>
div.container{width:86% !important;}
div.cell.code_cell.rendered{width:100%;}
div.CodeMirror {font-family:Consolas; font-size:15pt;}
div.output {font-size:15pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:15pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:15px;}
</style>
"""))

In [2]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from bs4 import BeautifulSoup
from urllib.request import urlopen
import math
import time
import requests
import pandas as pd

kospi, kosdak, divident = 'gsum', 'ksd_gsum', 'div'

C:\Users\Admin\anaconda3\lib\site-packages\requests\__init__.py:109: RequestsDependencyWarning: urllib3 (2.4.0) or chardet (4.0.0)/charset_normalizer (2.0.4) doesn't match a supported version!
  warnings.warn(

In [3]:
def load_csv_file(str):
    date = time.strftime("%y%m%d", time.localtime())
    item_list = pd.read_csv(f'data/naver/fin_{str}_{date}.csv', encoding='cp949') 
    return item_list

## 네이버 금융/주식/시가총액 화면

In [4]:
def call_nav_fin_gsum(string):

    driver = webdriver.Chrome()
    if(string == 'gsum'):
        driver.get('https://finance.naver.com/sise/sise_market_sum.naver?sosok=0')
    elif(string == 'ksd_gsum'):
        driver.get('https://finance.naver.com/sise/sise_market_sum.naver?sosok=1')
    time.sleep(0.5) # 초기화면 접근

    no_tgl_bxs = len(driver.find_elements(By.CSS_SELECTOR, 'td > input[type="checkbox"]'))
    toggle_boxes = [f'option{i}' for i in range(1, no_tgl_bxs+1)] # 체크박스 이름 준비

    pageN = 10
    max_tgl = 6
    item_list = pd.DataFrame([])
    for page in range(1,pageN+1):
        page_item_list = []
        for sheet in range(0, math.ceil(no_tgl_bxs/max_tgl)):
            dflt_toggle_boxes = driver.find_elements(By.CSS_SELECTOR, 'td.choice > input[type="checkbox"]')
            [elem.send_keys(Keys.SPACE) for elem in dflt_toggle_boxes]
            time.sleep(0.5) # 디폴트 체크박스 toggle

            sheet_toggle_boxes = toggle_boxes[sheet*max_tgl:min((sheet+1)*max_tgl, no_tgl_bxs+1)]
            new_toggle_boxes = [select_box for select_box in sheet_toggle_boxes]
            [driver.find_element(By.ID, box_id).send_keys(Keys.SPACE) for box_id in new_toggle_boxes]
            time.sleep(0.5) # 시트별 새로운 체크박스 toggle
            driver.find_element(By.CSS_SELECTOR, 'div.item_btn > a').click()
            time.sleep(0.5) # 토글 체크후 submit버튼 클릭

            soup = BeautifulSoup(driver.page_source, 'html.parser')
            table_head = [e.text.strip() for e in soup.select('thead > tr >th')][:-1]
            table_head.insert(3, '전일비변동')
            items = soup.select('tbody > tr') # 테이블 헤드 수집
            sheet_item_list = []
            for idx, item in enumerate(items):
                if(item.select_one('td.no')):
                    no = item.select_one('td.no').text
                    title = item.select_one('a.tltle').text
                    price_vals = [e.text.strip() for e in item.select('td.number')]
                    if(price_vals[1].strip()=='보합0'):
                        price_vals[1]=['보합',0]
                    else:
                        price_vals[1] = [price_vals[1].split('\n')[0], price_vals[1].split('\n')[1].strip()]

                    price_vals.insert(0, no)
                    price_vals.insert(1, title)
                    temp = price_vals[3][1]
                    price_vals.insert(3,price_vals[3][0])
                    price_vals[4] = temp

                    sheet_item_list.append(price_vals) # 테이블 내용 수집 
            sheet_item_df = pd.DataFrame(sheet_item_list, columns=table_head)

            if sheet == 0:
                page_item_list = sheet_item_df
            elif sheet < round(no_tgl_bxs/max_tgl):
                page_item_list = pd.concat([page_item_list, sheet_item_df[table_head[7:13]]], axis=1)
            else: 
                page_item_list = pd.concat([page_item_list, sheet_item_df[table_head[7:9]]], axis=1)
                # 페이지 내 시트 축적
        item_list = pd.concat([item_list, page_item_list], axis=0) # 페이지 내용 축적

        page_div = driver.find_element(By.CSS_SELECTOR, 'table.Nnavi > tbody > tr')
        if(page<pageN): # 지정 마지막 페이지 초과(pageN+1) 이동 금지
            page_div.find_element(By.LINK_TEXT, str(page+1)).click()
            time.sleep(1.5) # next page로
    print(f'~~ 총 {page}페이지 {sheet}시트 데이터를 수집 하였습니다~~')

    item_list.to_csv(f'data/naver/fin_{string}_{time.strftime("%y%m%d", time.localtime())}.csv', index=False, encoding='cp949')
    item_list.sample(10)

## 네이버 배당 화면 접근

In [5]:
def call_nav_fin_divident(string):
    driver = webdriver.Chrome()
    driver.get('https://finance.naver.com/sise/dividend_list.naver')
    time.sleep(0.5)

    pageN = 10
    item_list = []
    for page in range(1,pageN+1):
        soup = BeautifulSoup(driver.page_source, 'html.parser')
        table_head = [e.text.strip() for e in soup.select('thead > tr > th')]
        table_head[9] = '과거3년배당금_Max'
        


        items = soup.select('table.type_1.tb_ty> tbody > tr')
        for idx, item in enumerate(items):
            if(item.text.strip()):
                price_vals = [e.text.strip().replace(',','').replace('-','0') for e in item.select('td')]
                price_vals.insert(9, max(price_vals[9:12]))

                item_list.append({table_head[i]:e for i, e in enumerate(price_vals)})

        # next page로
        page_div = driver.find_element(By.CSS_SELECTOR, 'table.Nnavi > tbody > tr')
        if(page<pageN): # 지정 마지막 페이지 초과(pageN+1) 이동 금지
            page_div.find_element(By.LINK_TEXT, str(page+1)).click()
            time.sleep(1.5)
            
    print(f'~~ 총 {page}페이지 데이터를 수집 하였습니다~~')
    df = pd.DataFrame(item_list)
    df.to_csv(f'data/naver/fin_{string}_{time.strftime("%y%m%d", time.localtime())}.csv', index=False, encoding='cp949')

In [6]:
call_nav_fin_gsum(kospi)
call_nav_fin_gsum(kosdak)
call_nav_fin_divident(divident)

kospi_item_list = load_csv_file(kospi)
kosdak_item_list = load_csv_file(kosdak)
divident_item_list = load_csv_file(divident)

kosdak_item_list.tail(3)

selected_divident_items = divident_item_list[(divident_item_list['수익률(%)']>=5.0) &
                                             (divident_item_list['ROE(%)']>=5.0) &
                                             (divident_item_list['PER(배)']<=10.0) &
                                             (divident_item_list['PBR(배)']<=1.0) &
                                             (divident_item_list['배당성향(%)']>=25.0)]
display(selected_divident_items)
p_kospi = kospi_item_list[kospi_item_list['전일비변동']=='하락'].sort_values('등락률', ascending=False)
p_kosdak = kosdak_item_list[kosdak_item_list['전일비변동']=='하락'].sort_values('등락률', ascending=False)
proposed_kospi = pd.merge(selected_divident_items, p_kospi, how='inner', on=['종목명'])
proposed_kosdak = pd.merge(selected_divident_items, p_kosdak, how='inner', on=['종목명'])

display(proposed_kospi.T)
display(proposed_kosdak.T)

~~ 총 10페이지 4시트 데이터를 수집 하였습니다~~
~~ 총 10페이지 4시트 데이터를 수집 하였습니다~~
~~ 총 10페이지 데이터를 수집 하였습니다~~

,종목명,현재가,기준월,배당금,수익률(%),배당성향(%),ROE(%),PER(배),PBR(배),과거3년배당금_Max,1년전,2년전,3년전
1,레드캡투어,11900,25.03,2150,18.07,177.53,9.64,7.26,0.67,450,450,450,400
13,정다운,2690,24.12,250,9.29,68.61,9.33,7.31,0.65,300,300,100,100
14,HB인베스트먼트,2205,24.12,200,9.07,89.81,8.28,6.99,0.49,0,0,0,0
19,현대해상,25350,24.03,2063,8.14,28.16,7.38,4.82,0.40,1965,1965,1480,1000
22,영보화학,4455,24.12,350,7.86,30.26,13.01,3.16,0.38,50,50,50,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,한일현대시멘트,17250,24.12,900,5.22,28.97,14.60,4.36,0.61,700,700,600,1200
156,YW,3840,24.12,200,5.21,37.63,5.31,9.62,0.36,200,200,150,100
158,코리안리,9990,25.04,515,5.16,28.74,9.44,4.89,0.41,458,458,311,324
167,대상우,17000,25.03,860,5.06,32.18,6.94,7.26,0.49,810,810,810,810
173,미원화학,80000,24.12,4000,5.00,29.79,17.55,6.44,0.98,3500,3500,2500,2500

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
종목명,현대차우,현대차2우B,기아,강원랜드,LX인터내셔널,삼성화재우,이노션,현대차,삼성카드,동양생명,BNK금융지주,한일시멘트,삼성증권,코리안리
현재가_x,158300,159400,98200,18000,31000,321000,20000,206750,48500,7010,11750,18170,66900,9990
기준월,25.02,25.02,25.03,25.04,25.02,25.03,25.03,25.02,25.03,24.04,25.02,24.12,24.12,25.04
배당금,12050,12100,6500,1170,2000,19005,1175,12000,2800,400,650,1000,3500,515
수익률(%),7.61,7.59,6.62,6.5,6.45,5.92,5.88,5.8,5.77,5.71,5.53,5.5,5.23,5.16
배당성향(%),25.13,25.13,26.18,51.32,40.94,38.95,46.88,25.13,44.96,26.01,28.46,37.63,34.76,28.74
ROE(%),12.43,12.43,19.09,12.08,7.12,13.11,10.48,12.43,8.0,6.18,6.96,11.13,12.89,9.44
PER(배),4.6,4.6,4.12,7.48,5.97,8.74,7.74,4.6,6.88,3.05,4.56,5.46,4.32,4.89
PBR(배),0.51,0.51,0.71,0.82,0.37,0.98,0.77,0.51,0.5,0.25,0.31,0.58,0.53,0.41
과거3년배당금_Max,7050,7100,5600,930,3000,16005,900,7000,2500,620,625,800,3800,458
1년전,11450,11500,5600,930,1200,16005,1175,11400,2500,0,510,800,2200,458
2년전,7050,7100,3500,350,3000,13805,1075,7000,2500,620,625,580,1700,311
3년전,5050,5100,3000,0,2300,12005,900,5000,2300,220,560,540,3800,324
N,112,86,10,109,240,269,313,6,85,245,111,232,81,175
현재가_y,"158,200","159,300","98,000","17,960","30,850","321,500","20,050","206,500","48,600","7,020","11,740","18,130","66,700","10,000"
전일비변동,하락,하락,하락,하락,하락,하락,하락,하락,하락,하락,하락,하락,하락,하락
전일비,600,"1,000",200,100,400,500,100,500,350,50,50,190,600,50
등락률,-0.38%,-0.62%,-0.20%,-0.55%,-1.28%,-0.16%,-0.50%,-0.24%,-0.72%,-0.71%,-0.42%,-1.04%,-0.89%,-0.50%
액면가,"5,000","5,000","5,000",500,"5,000",500,500,"5,000","5,000","5,000","5,000",500,"5,000",500
거래량,"11,299","15,978","88,394","72,622","20,453","1,094","34,492","60,106","7,243","16,766","93,095","5,663","63,707","28,990"
거래대금,"1,788","2,544","8,654","1,307",634,351,692,"12,409",352,117,"1,091",103,"4,273",289
매수호가,"158,700","159,600","98,200","17,960","31,000","321,000","20,000","207,000","48,650","7,000","11,690","18,220","66,700","9,960"
시가총액,"36,925","55,698","389,719","38,424","11,957","9,965","8,020","422,825","56,307","11,327","37,378","12,557","59,563","19,482"
영업이익,NaN,NaN,"126,671","2,858","4,892",NaN,"1,557","142,396","8,854","3,681","8,759","2,714","12,058","4,054"
PER,3.45,3.47,4.18,8.76,6.12,8.21,9.26,4.50,8.39,4.08,5.83,8.95,6.66,5.51
전일거래량,"79,522","80,966","691,399","581,576","127,314","5,947","629,403","538,891","112,599","162,454","688,590","62,391","417,694","185,581"
시가,"158,900","160,900","98,000","18,110","31,250","322,000","20,200","208,000","49,200","7,010","11,800","18,360","67,700","10,060"
매도호가,"158,800","159,700","98,300","17,980","31,050","322,000","20,050","207,500","48,700","7,020","11,700","18,230","66,900","9,990"
자산총계,NaN,NaN,"927,559","47,006","89,309",NaN,"27,146","3,397,984","294,941","345,472","1,524,705","29,883","622,739","131,604"
영업이익증가율,NaN,NaN,9.13,1.25,12.95,NaN,3.76,-5.87,9.31,25.08,9.33,10.09,62.69,11.48
ROE,NaN,NaN,19.09,12.09,7.12,NaN,10.48,12.43,8.0,12.91,6.96,11.13,12.89,9.45
고가,"159,000","160,900","98,500","18,120","31,300","323,000","20,200","208,000","49,200","7,050","11,840","18,370","67,800","10,060"
매수총잔량,"1,047","3,740","10,319","5,457","6,627",552,"4,134","17,504",497,"6,102","9,164","1,426","7,604","9,069"
부채총계,NaN,NaN,"369,156","8,170","56,113",NaN,"16,827","2,195,225","210,079","325,805","1,413,229","11,495","549,497","97,075"
당기순이익,NaN,NaN,"97,750","4,569","2,695",NaN,"1,161","132,299","6,646","3,143","7,500","1,990","8,990","3,167"
외국인비율,61.34,60.18,39.03,13.85,21.55,28.88,25.74,36.2,6.27,81.36,40.27,4.7,28.88,27.8
ROA,NaN,NaN,11.28,9.99,3.18,NaN,4.4,4.25,2.28,0.93,0.5,6.8,1.51,2.51
저가,"157,700","158,800","97,200","17,920","30,800","320,000","19,970","205,500","48,300","6,940","11,660","18,100","66,500","9,950"
매도총잔량,950,306,"18,127","2,604","3,506",875,"5,714","31,788",758,"2,275","7,039",430,"5,937","7,238"
상장주식수,"23,341","34,964","397,673","213,940","38,760","3,100","40,000","204,758","115,859","161,359","318,384","69,262","89,300","194,821"
매출액,NaN,NaN,"1,074,488","14,269","166,376",NaN,"21,206","1,752,312","43,832","34,994","100,314","17,417","134,666","69,579"
주당순이익,"45,880","45,880","23,440","2,050","5,044","39,171","2,166","45,880","5,793","1,722","2,012","2,025","10,015","1,816"
PBR,0.37,0.38,0.69,0.97,0.41,0.89,0.81,0.49,0.62,0.76,0.36,0.76,0.82,0.52
보통주배당금,NaN,NaN,"6,500","1,170","2,000",NaN,"1,175","12,000","2,800",NaN,650,"1,000","3,500",515
매출액증가율,NaN,NaN,7.66,2.76,14.63,NaN,1.32,7.73,9.47,7.65,3.8,-3.21,2.26,-0.08

                  0        1       2       3
종목명             노바텍   에스에이엠티   멀티캠퍼스     골프존
현재가_x         18250     2915   34350   66300
기준월           24.12    24.12   24.12   24.12
배당금            1409      200    2100    4000
수익률(%)         7.72     6.86    6.11    6.03
배당성향(%)       80.44    35.89   40.06   48.23
ROE(%)         10.8    13.46   15.16   11.62
PER(배)         8.95     4.79     5.7    8.24
PBR(배)         0.87     0.59    0.82    0.89
과거3년배당금_Max     500      230     800    4500
1년전             500      200    1600    4500
2년전             200      230     800    4500
3년전             143      200     600    3500
N               450      271     416     178
현재가_y        18,250    2,910  34,350  66,300
전일비변동            하락       하락      하락      하락
전일비             100        5     100     200
등락률          -0.54%   -0.17%  -0.29%  -0.30%
액면가             500      500     500     500
거래량          11,746   25,192   1,891   1,585
거래대금            215       74      65     105
매수호가         18,340    2,920  34,500  66,500
시가총액          1,930    2,910   2,036   4,161
영업이익            126      674     389     958
PER           12.94     5.79    6.91    8.30
전일거래량        59,022  182,019   5,261  21,983
시가           18,530    2,915  34,600  66,500
매도호가         18,510    2,925  34,550  66,600
자산총계          1,834    8,330   3,207   6,655
영업이익증가율      -50.75    25.83   -3.37  -16.34
ROE            10.8    13.46   15.16   11.63
고가           18,550    2,935  34,650  66,600
매수총잔량           624   46,015   1,035     671
부채총계            125    4,024     997   2,188
당기순이익           172      544     315     420
외국인비율          1.76     5.38    7.55   23.02
ROA            9.78     7.23    9.97    6.45
저가           18,200    2,905  34,150  66,000
매도총잔량         1,091   25,142     995     285
상장주식수        10,576   99,995   5,927   6,275
매출액             658   28,895   3,527   6,200
주당순이익         1,410      503   4,970   7,991
PBR            1.17     0.67    0.98    0.91
보통주배당금        1,409      200   2,100   4,000
매출액증가율       -28.79    34.70   -1.63   -9.51