In [1]:
from IPython.display import display, HTML 
display(HTML("""
<style>
div.container{width:86% !important;}
div.cell.code_cell.rendered{width:100%;}
div.CodeMirror {font-family:Consolas; font-size:15pt;}
div.output {font-size:15pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:15pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:15px;}
</style>
"""))

In [2]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from bs4 import BeautifulSoup
from urllib.request import urlopen
import math
import time
import requests
import pandas as pd

kospi, kosdak, divident = 'gsum', 'ksd_gsum', 'div'

C:\Users\Admin\anaconda3\lib\site-packages\requests\__init__.py:109: RequestsDependencyWarning: urllib3 (2.4.0) or chardet (4.0.0)/charset_normalizer (2.0.4) doesn't match a supported version!
  warnings.warn(

In [8]:
call_nav_fin_gsum(kospi)
call_nav_fin_gsum(kosdak)
call_nav_fin_divident(divident)

kospi_item_list = load_csv_file(kospi)
kosdak_item_list = load_csv_file(kosdak)
divident_item_list = load_csv_file(divident)

kosdak_item_list.tail(3)

selected_divident_items = divident_item_list[(divident_item_list['수익률(%)']>=5.0) &
                                             (divident_item_list['ROE(%)']>=5.0) &
                                             (divident_item_list['PER(배)']<=10.0) &
                                             (divident_item_list['PBR(배)']<=1.0) &
                                             (divident_item_list['배당성향(%)']>=25.0)]
display(selected_divident_items)
p_kospi = kospi_item_list[kospi_item_list['전일비변동']=='하락'].sort_values('등락률', ascending=False)
p_kosdak = kosdak_item_list[kosdak_item_list['전일비변동']=='하락'].sort_values('등락률', ascending=False)
proposed_kospi = pd.merge(selected_divident_items, p_kospi, how='inner', on=['종목명'])
proposed_kosdak = pd.merge(selected_divident_items, p_kosdak, how='inner', on=['종목명'])

display(proposed_kospi.T)
display(proposed_kosdak.T)

~~ 총 10페이지 4시트 데이터를 수집 하였습니다~~
~~ 총 10페이지 4시트 데이터를 수집 하였습니다~~
~~ 총 10페이지 데이터를 수집 하였습니다~~

,종목명,현재가,기준월,배당금,수익률(%),배당성향(%),ROE(%),PER(배),PBR(배),과거3년배당금_Max,1년전,2년전,3년전
6,크레버스,14255,25.04,1500,10.52,167.06,17.99,21.71,3.06,2000,2000,1800,2000
8,이크레더블,15820,24.12,1590,10.05,148.28,27.34,12.07,3.18,780,780,1040,2720
16,정상제이엘에스,6160,24.12,530,8.60,94.60,9.05,12.55,1.08,530,530,530,530
37,케이카,15600,24.12,1150,7.37,126.03,19.09,14.04,2.73,760,760,760,750
54,현대엘리베이터,79600,24.12,5500,6.91,108.40,14.42,11.18,1.51,800,4000,500,800
61,디지털대성,7410,24.12,500,6.75,86.41,10.45,12.59,1.36,300,200,200,300
78,한국쉘석유,422500,24.12,27000,6.39,95.76,28.93,11.30,3.25,25000,25000,18000,19000
96,진양폴리,4070,24.12,250,6.14,79.02,9.74,20.99,2.03,250,250,200,175
108,효성ITX,12460,24.12,750,6.02,75.93,16.71,12.90,2.06,750,750,750,750
118,진로발효,18560,24.12,1100,5.93,71.02,12.59,10.92,1.29,650,650,450,1150
130,화인써키트,6110,24.12,350,5.73,91.46,10.18,15.42,1.51,431,400,431,35
135,에이블씨엔씨,7260,25.03,411,5.66,73.50,16.26,12.48,1.99,1427,1427,0,0
138,에코마케팅,8870,24.12,500,5.64,52.30,12.87,10.68,1.30,310,200,310,310
141,한전KPS,44000,24.12,2469,5.61,64.43,13.26,11.51,1.49,2158,2158,1305,1199
157,모나리자,2840,24.03,150,5.28,59.97,11.51,10.50,1.18,75,50,0,75

                   0        1
종목명              케이카    한전KPS
현재가_x          15600    44000
기준월            24.12    24.12
배당금             1150     2469
수익률(%)          7.37     5.61
배당성향(%)       126.03    64.43
ROE(%)         19.09    13.26
PER(배)         14.04    11.51
PBR(배)          2.73     1.49
과거3년배당금_Max      760     2158
1년전              760     2158
2년전              760     1305
3년전              750     1199
N                329      172
현재가_y         15,600   44,000
전일비변동             하락       하락
전일비              150      500
등락률           -0.95%   -1.12%
액면가              500      200
거래량          229,963  202,250
거래대금           3,576    8,939
매수호가          15,580   43,750
시가총액           7,516   19,800
영업이익             681    2,095
PER            16.12    14.13
전일거래량        237,939  441,975
시가            15,700   44,100
매도호가          15,590   43,800
자산총계           5,248   16,902
영업이익증가율        15.41     5.08
ROE            19.09    13.26
고가            15,700   44,950
매수총잔량          3,779   10,211
부채총계           2,991    3,617
당기순이익            440    1,724
외국인비율           7.53    15.28
ROA             8.15    10.49
저가            15,300   43,600
매도총잔량          2,185    5,305
상장주식수         48,182   45,000
매출액           23,015   15,571
주당순이익            968    3,113
PBR             3.37     1.62
보통주배당금         1,150    2,469
매출액증가율          12.4     1.52

                  0       1
종목명           이크레더블   디지털대성
현재가_x         15820    7410
기준월           24.12   24.12
배당금            1590     500
수익률(%)        10.05    6.75
배당성향(%)      148.28   86.41
ROE(%)        27.34   10.45
PER(배)        12.07   12.59
PBR(배)         3.18    1.36
과거3년배당금_Max     780     300
1년전             780     200
2년전            1040     200
3년전            2720     300
N               440     408
현재가_y        15,820   7,410
전일비변동            하락      하락
전일비              20      40
등락률          -0.13%  -0.54%
액면가             500     500
거래량          16,812  38,235
거래대금            266     284
매수호가         15,830   7,420
시가총액          1,905   2,051
영업이익            150     237
PER           14.61   12.71
전일거래량        13,495  54,496
시가           15,850   7,460
매도호가         15,840   7,430
자산총계            594   3,380
영업이익증가율       18.68   -5.28
ROE           27.34   10.45
고가           15,880   7,630
매수총잔량         1,963   4,802
부채총계            104   1,769
당기순이익           129     161
외국인비율          8.89    3.14
ROA           22.74    5.49
저가           15,800   7,320
매도총잔량         9,730   1,034
상장주식수        12,044  27,675
매출액             451   2,177
주당순이익         1,083     583
PBR            6.27     1.6
보통주배당금        1,590     500
매출액증가율         9.70    2.92

In [9]:
selected_divident_items = divident_item_list[(divident_item_list['수익률(%)']>=5.0) &
                                             (divident_item_list['ROE(%)']>=5.0) &
                                             (divident_item_list['PER(배)']<=10.0) &
                                             (divident_item_list['PBR(배)']<=1.0) &
                                             (divident_item_list['배당성향(%)']>=25.0)]
display(selected_divident_items)
p_kospi = kospi_item_list[kospi_item_list['전일비변동']=='하락'].sort_values('등락률', ascending=False)
p_kosdak = kosdak_item_list[kosdak_item_list['전일비변동']=='하락'].sort_values('등락률', ascending=False)
proposed_kospi = pd.merge(selected_divident_items, p_kospi, how='inner', on=['종목명'])
proposed_kosdak = pd.merge(selected_divident_items, p_kosdak, how='inner', on=['종목명'])

display(proposed_kospi.T)
display(proposed_kosdak.T)

,종목명,현재가,기준월,배당금,수익률(%),배당성향(%),ROE(%),PER(배),PBR(배),과거3년배당금_Max,1년전,2년전,3년전
2,레드캡투어,12670,25.03,2150,16.97,177.53,9.64,7.26,0.67,450,450,450,400
10,HB인베스트먼트,2070,24.12,200,9.66,89.81,8.28,6.99,0.49,0,0,0,0
13,정다운,2725,24.12,250,9.17,68.61,9.33,7.31,0.65,300,300,100,100
17,현대해상,24800,24.03,2063,8.32,28.16,7.38,4.82,0.40,1965,1965,1480,1000
21,현대차우,152100,25.02,12050,7.92,25.13,12.43,4.60,0.51,7050,11450,7050,5050
...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,NH투자증권,18230,25.03,950,5.21,47.96,8.73,7.06,0.59,800,800,700,1050
162,YW,3845,24.12,200,5.20,37.63,5.31,9.62,0.36,200,200,150,100
163,JB금융지주,19190,25.02,995,5.18,28.00,12.80,4.69,0.55,855,855,835,599
166,웅진씽크빅,1750,24.12,90,5.14,52.12,6.44,9.30,0.60,130,0,110,130
176,대상우,17090,25.03,860,5.03,32.18,6.94,7.26,0.49,810,810,810,810

,0,1,2,3,4,5,6,7,8,9,10
종목명,현대해상,현대차우,현대차2우B,기아,강원랜드,SK텔레콤,삼성화재우,현대차,삼성증권,한국앤컴퍼니,코리안리
현재가_x,24800,152100,153200,94400,17350,52700,307500,196700,63300,18750,9870
기준월,24.03,25.02,25.02,25.03,25.04,25.02,25.03,25.02,24.12,25.03,25.04
배당금,2063,12050,12100,6500,1170,3540,19005,12000,3500,1000,515
수익률(%),8.32,7.92,7.9,6.89,6.74,6.72,6.18,6.1,5.53,5.33,5.22
배당성향(%),28.16,25.13,25.13,26.18,51.32,60.28,38.95,25.13,34.76,27.01,28.74
ROE(%),7.38,12.43,12.43,19.09,12.08,10.83,13.11,12.43,12.89,8.28,9.44
PER(배),4.82,4.6,4.6,4.12,7.48,9.5,8.74,4.6,4.32,4.58,4.89
PBR(배),0.4,0.51,0.51,0.71,0.82,1.0,0.98,0.51,0.53,0.36,0.41
과거3년배당금_Max,1965,7050,7100,5600,930,3540,16005,7000,3800,700,458
1년전,1965,11450,11500,5600,930,3540,16005,11400,2200,700,458
2년전,1480,7050,7100,3500,350,3320,13805,7000,1700,650,311
3년전,1000,5050,5100,3000,0,2660,12005,5000,3800,600,324
N,151,113,86,10,108,45,275,7,82,183,179
현재가_y,"24,800","152,100","153,200","94,400","17,350","52,700","307,500","196,700","63,300","18,750","9,870"
전일비변동,하락,하락,하락,하락,하락,하락,하락,하락,하락,하락,하락
전일비,300,"2,800","2,300",900,40,400,"6,000","1,100",200,120,60
등락률,-1.20%,-1.81%,-1.48%,-0.94%,-0.23%,-0.75%,-1.91%,-0.56%,-0.31%,-0.64%,-0.60%
액면가,500,"5,000","5,000","5,000",500,100,500,"5,000","5,000",500,500
거래량,"463,410","107,987","148,783","939,240","370,168","839,636","18,115","909,421","426,712","262,768","366,328"
거래대금,"11,576","16,603","22,988","89,097","6,422","44,376","5,598","179,756","27,037","4,975","3,599"
매수호가,"24,750","152,000","153,100","94,300","17,310","52,700","306,000","196,700","63,000","18,690","9,800"
시가총액,"22,171","35,502","53,565","375,403","37,119","113,194","9,531","402,759","56,527","17,800","19,229"
영업이익,"12,441",NaN,NaN,"126,671","2,858","18,234",NaN,"142,396","12,058","4,183","4,054"
PER,2.61,3.32,3.34,4.03,8.46,8.97,7.50,4.29,6.32,5.06,6.07
전일거래량,"600,970","136,965","247,825","1,449,046","710,547","939,726","22,616","1,665,140","737,085","298,641","488,370"
시가,"25,200","155,700","156,600","96,200","17,450","53,200","315,000","201,000","64,100","19,030","9,900"
매도호가,"24,800","152,100","153,200","94,400","17,320","52,800","306,500","196,600","63,100","18,710","9,810"
자산총계,"485,238",NaN,NaN,"927,559","47,006","305,153",NaN,"3,397,984","622,739","51,364","131,604"
영업이익증가율,67.33,NaN,NaN,9.13,1.25,4.00,NaN,-5.87,62.69,63.03,11.48
ROE,15.75,NaN,NaN,19.09,12.09,10.83,NaN,12.43,12.89,8.28,9.45
고가,"25,450","156,200","156,900","96,400","17,450","53,300","315,500","201,500","64,500","19,230","9,990"
매수총잔량,"36,133","3,649","4,846","53,462","11,551","124,212",761,"22,338","12,400","1,796","6,556"
부채총계,"437,804",NaN,NaN,"369,156","8,170","186,876",NaN,"2,195,225","549,497","6,836","97,075"
당기순이익,"8,505",NaN,NaN,"97,750","4,569","13,871",NaN,"132,299","8,990","3,507","3,167"
외국인비율,35.19,61.52,60.14,38.62,13.58,39.83,27.9,35.78,29.61,10.17,27.3
ROA,1.84,NaN,NaN,11.28,9.99,4.58,NaN,4.25,1.51,7.17,2.51
저가,"24,650","151,900","153,000","94,100","17,250","52,600","305,000","195,800","62,000","18,600","9,720"
매도총잔량,"37,400","1,348","1,013","14,468","18,373","76,426",323,"7,795","4,932",961,"9,214"
상장주식수,"89,400","23,341","34,964","397,673","213,940","214,790","3,100","204,758","89,300","94,935","194,821"
매출액,"173,245",NaN,NaN,"1,074,488","14,269","179,406",NaN,"1,752,312","134,666","13,910","69,579"
주당순이익,"9,514","45,880","45,880","23,440","2,050","5,874","41,007","45,880","10,015","3,709","1,625"
PBR,0.41,0.36,0.36,0.66,0.94,0.95,0.84,0.46,0.78,0.4,0.51
보통주배당금,NaN,NaN,NaN,"6,500","1,170","3,540",NaN,"12,000","3,500","1,000",515
매출액증가율,8.86,NaN,NaN,7.66,2.76,1.89,NaN,7.73,2.26,27.65,-0.08

                   0        1       2
종목명              노바텍   에스에이엠티     골프존
현재가_x          18260     2825   67700
기준월            24.12    24.12   24.12
배당금             1409      200    4000
수익률(%)          7.72     7.08    5.91
배당성향(%)        80.44    35.89   48.23
ROE(%)          10.8    13.46   11.62
PER(배)          8.95     4.79    8.24
PBR(배)          0.87     0.59    0.89
과거3년배당금_Max      500      230    4500
1년전              500      200    4500
2년전              200      230    4500
3년전              143      200    3500
N                435      277     173
현재가_y         18,260    2,825  67,700
전일비변동             하락       하락      하락
전일비              150       25     200
등락률           -0.81%   -0.88%  -0.29%
액면가              500      500     500
거래량          123,060  273,876  13,725
거래대금           2,263      777     935
매수호가          18,250    2,820  67,600
시가총액           1,931    2,825   4,248
영업이익             126      674     958
PER            12.95     5.62    8.47
전일거래량        169,778  383,328  21,287
시가            18,600    2,850  68,400
매도호가          18,270    2,825  67,700
자산총계           1,834    8,330   6,655
영업이익증가율       -50.75    25.83  -16.34
ROE             10.8    13.46   11.63
고가            18,740    2,855  68,700
매수총잔량          3,027  147,245     998
부채총계             125    4,024   2,188
당기순이익            172      544     420
외국인비율           1.07     5.47   22.58
ROA             9.78     7.23    6.45
저가            18,140    2,815  67,600
매도총잔량          1,255   57,948   1,246
상장주식수         10,576   99,995   6,275
매출액              658   28,895   6,200
주당순이익          1,410      503   7,991
PBR             1.17     0.65    0.93
보통주배당금         1,409      200   4,000
매출액증가율        -28.79    34.70   -9.51

In [3]:
def load_csv_file(str):
    date = time.strftime("%y%m%d", time.localtime())
    item_list = pd.read_csv(f'data/naver/fin_{str}_{date}.csv', encoding='cp949') 
    return item_list

## 네이버 금융/주식/시가총액 화면

In [4]:
def call_nav_fin_gsum(string):

    driver = webdriver.Chrome()
    if(string == 'gsum'):
        driver.get('https://finance.naver.com/sise/sise_market_sum.naver?sosok=0')
    elif(string == 'ksd_gsum'):
        driver.get('https://finance.naver.com/sise/sise_market_sum.naver?sosok=1')
    time.sleep(0.5) # 초기화면 접근

    no_tgl_bxs = len(driver.find_elements(By.CSS_SELECTOR, 'td > input[type="checkbox"]'))
    toggle_boxes = [f'option{i}' for i in range(1, no_tgl_bxs+1)] # 체크박스 이름 준비

    pageN = 10
    max_tgl = 6
    item_list = pd.DataFrame([])
    for page in range(1,pageN+1):
        page_item_list = []
        for sheet in range(0, math.ceil(no_tgl_bxs/max_tgl)):
            dflt_toggle_boxes = driver.find_elements(By.CSS_SELECTOR, 'td.choice > input[type="checkbox"]')
            [elem.send_keys(Keys.SPACE) for elem in dflt_toggle_boxes]
            time.sleep(0.5) # 디폴트 체크박스 toggle

            sheet_toggle_boxes = toggle_boxes[sheet*max_tgl:min((sheet+1)*max_tgl, no_tgl_bxs+1)]
            new_toggle_boxes = [select_box for select_box in sheet_toggle_boxes]
            [driver.find_element(By.ID, box_id).send_keys(Keys.SPACE) for box_id in new_toggle_boxes]
            time.sleep(0.5) # 시트별 새로운 체크박스 toggle
            driver.find_element(By.CSS_SELECTOR, 'div.item_btn > a').click()
            time.sleep(0.5) # 토글 체크후 submit버튼 클릭

            soup = BeautifulSoup(driver.page_source, 'html.parser')
            table_head = [e.text.strip() for e in soup.select('thead > tr >th')][:-1]
            table_head.insert(3, '전일비변동')
            items = soup.select('tbody > tr') # 테이블 헤드 수집
            sheet_item_list = []
            for idx, item in enumerate(items):
                if(item.select_one('td.no')):
                    no = item.select_one('td.no').text
                    title = item.select_one('a.tltle').text
                    price_vals = [e.text.strip() for e in item.select('td.number')]
                    if(price_vals[1].strip()=='보합0'):
                        price_vals[1]=['보합',0]
                    else:
                        price_vals[1] = [price_vals[1].split('\n')[0], price_vals[1].split('\n')[1].strip()]

                    price_vals.insert(0, no)
                    price_vals.insert(1, title)
                    temp = price_vals[3][1]
                    price_vals.insert(3,price_vals[3][0])
                    price_vals[4] = temp

                    sheet_item_list.append(price_vals) # 테이블 내용 수집 
            sheet_item_df = pd.DataFrame(sheet_item_list, columns=table_head)

            if sheet == 0:
                page_item_list = sheet_item_df
            elif sheet < round(no_tgl_bxs/max_tgl):
                page_item_list = pd.concat([page_item_list, sheet_item_df[table_head[7:13]]], axis=1)
            else: 
                page_item_list = pd.concat([page_item_list, sheet_item_df[table_head[7:9]]], axis=1)
                # 페이지 내 시트 축적
        item_list = pd.concat([item_list, page_item_list], axis=0) # 페이지 내용 축적

        page_div = driver.find_element(By.CSS_SELECTOR, 'table.Nnavi > tbody > tr')
        if(page<pageN): # 지정 마지막 페이지 초과(pageN+1) 이동 금지
            page_div.find_element(By.LINK_TEXT, str(page+1)).click()
            time.sleep(1.5) # next page로
    print(f'~~ 총 {page}페이지 {sheet}시트 데이터를 수집 하였습니다~~')

    item_list.to_csv(f'data/naver/fin_{string}_{time.strftime("%y%m%d", time.localtime())}.csv', index=False, encoding='cp949')
    item_list.sample(10)

## 네이버 배당 화면 접근

In [5]:
def call_nav_fin_divident(string):
    driver = webdriver.Chrome()
    driver.get('https://finance.naver.com/sise/dividend_list.naver')
    time.sleep(0.5)

    pageN = 10
    item_list = []
    for page in range(1,pageN+1):
        soup = BeautifulSoup(driver.page_source, 'html.parser')
        table_head = [e.text.strip() for e in soup.select('thead > tr > th')]
        table_head[9] = '과거3년배당금_Max'
        


        items = soup.select('table.type_1.tb_ty> tbody > tr')
        for idx, item in enumerate(items):
            if(item.text.strip()):
                price_vals = [e.text.strip().replace(',','').replace('-','0') for e in item.select('td')]
                price_vals.insert(9, max(price_vals[9:12]))

                item_list.append({table_head[i]:e for i, e in enumerate(price_vals)})

        # next page로
        page_div = driver.find_element(By.CSS_SELECTOR, 'table.Nnavi > tbody > tr')
        if(page<pageN): # 지정 마지막 페이지 초과(pageN+1) 이동 금지
            page_div.find_element(By.LINK_TEXT, str(page+1)).click()
            time.sleep(1.5)
            
    print(f'~~ 총 {page}페이지 데이터를 수집 하였습니다~~')
    df = pd.DataFrame(item_list)
    df.to_csv(f'data/naver/fin_{string}_{time.strftime("%y%m%d", time.localtime())}.csv', index=False, encoding='cp949')